name: simple ci

on:
  push:
    branches: [ "ForsakenCaptain-patch-dockerTest" ]
  pull_request:
    branches: [ "ForsakenCaptain-patch-dockerTest" ]

jobs:

# build:
  build:

    runs-on: ubuntu-latest

# tests:
    steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-java@v3
         with:
          java-version: '17'
          distribution: 'temurin'
#       - name: build with maven
#         run: mvn clean install

       - name: Run calculator test
         run: mvn test

# deploy:
#       - uses: actions/checkout@v3
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
       - name: publish to Docker hub
         uses: docker/build-push-action@v2
         with:
           Username: ${{ secrets.DOCKER_HUB_USERNAME }}
           Password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
           Repository: florisvander/testrepos1
           tags: ${{github.run_number}}