name: simple ci

on:
  push:
    branches: [ "ForsakenCaptain-patch-dockerTest" ]
  pull_request:
    branches: [ "ForsakenCaptain-patch-dockerTest" ]

jobs:

# build:
  build-and-deploy:

    runs-on: ubuntu-latest

# tests:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'

#       - name: build with maven
#         run: mvn clean install

      - name: Run tests
        run: mvn test

#      - name: Static code analysis
#        env:
#          GITHUB_TOKEN: "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"
#          SONAR_TOKEN: "6d27a781a47edfde6d2e9c1d11f8d9cbb68bf374"
#        run: mvn verify sonar:sonar \
#          -Dsonar.host.url=https://sonarcloud.io \
#          -Dsonar.organization= ForsakenCaptain_Smoke \
#          -Dsonar.projectkey= forsakencaptain

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: "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"  # Needed to get PR information, if any
          SONAR_TOKEN: "6d27a781a47edfde6d2e9c1d11f8d9cbb68bf374"
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ForsakenCaptain_Smoke

# deploy:
#       - uses: actions/checkout@v3
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Docker Build and Push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: florisvander/testrepos1:latest
#
#      - name: Docker Login
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}







      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
#            username: ${{ secrets.DOCKER_HUB_USERNAME }}
#            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            username: "florisvander"
            password: "Boxklonreng2"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: florisvander/testrepos1:latest

      - name: Logout from Docker registry
        run: docker logout https://hub.docker.com/

#      - name: publish to Docker hub
#        uses: docker/build-push-action@v4
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
#          repository: florisvander/testrepos1
#          tags: ${{github.run_number}}

#      - name: publish to Docker hub
#        uses: docker/build-push-action@v4
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
#          repository: florisvander/testrepos1
#          tags: ${{github.run_number}}