name: Docker Image CI

on:
  push:
    branches: [ "ForsakenCaptain-patch-dockerTest" ]
  pull_request:
    branches: [ "ForsakenCaptain-patch-dockerTest" ]

jobs:

# build:
  build:


    runs-on: ubuntu-latest

# tests:
    Steps:
    - name: Run calculator test
    -  run: mvn test

# deploy:
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
