name: simple ci

on:
  push:
    branches: [ "ForsakenCaptain-patch-dockerTest" ]
  pull_request:
    branches: [ "ForsakenCaptain-patch-dockerTest" ]

jobs:

# build:
  build:

    runs-on: ubuntu-latest

# tests:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'

#       - name: build with maven
#         run: mvn clean install

      - name: Run calculator test
        run: mvn test

# deploy:
#       - uses: actions/checkout@v3
#       - name: Build the Docker image
#         run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Docker Build and Push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: florisvander/testrepos1:latest
#
#      - name: Docker Login
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}







      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
           username: "489724@student.fontys.nl"
           password: "Boxklonreng2"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./testrepos1
          push: true
          tags: florisvander/testrepos1:latest

      - name: Logout from Docker registry
        run: docker logout https://hub.docker.com/



#      - name: publish to Docker hub
#        uses: docker/build-push-action@v4
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
#          repository: florisvander/testrepos1
#          tags: ${{github.run_number}}

#      - name: publish to Docker hub
#        uses: docker/build-push-action@v4
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
#          repository: florisvander/testrepos1
#          tags: ${{github.run_number}}